# podman-hpc build -t mjkramer/2x2_sim:core011 .
FROM mjkramer/2x2_sim:base011

RUN mkdir -p /build
WORKDIR /build
COPY *.sh .

RUN cat core.env.sh >> /opt/environment

RUN ./build_pythia6.sh
RUN ./build_root.sh
RUN ./build_lhapdf.sh
RUN ./build_genie.sh
RUN ./build_dk2nu.sh
RUN ./build_geant4.sh

WORKDIR /
RUN rm -rf /build
