# podman-hpc build -t mjkramer/2x2_sim:ndlar011 .
FROM mjkramer/2x2_sim:edepsim011

RUN mkdir -p /build
WORKDIR /build
COPY *.sh .
COPY flow_inputs flow_inputs

# RUN cat ndlar.env.sh >> /opt/environment

# RUN ./prep_ndlar.sh
RUN ./build_sim.sh
RUN ./build_flow.sh
RUN ./build_validation.sh

WORKDIR /
RUN rm -rf /build
