# podman-hpc build -t mjkramer/2x2_sim:base011 .
FROM fedora:37

RUN mkdir -p /build
WORKDIR /build
COPY *.sh .

RUN ./build_base.sh

# Interactive shells load our env via /etc/bashrc,
# login shells load our env via /etc/profile,
# in both cases via /etc/profile.d/zzz.load_env.sh.
# For non-login non-interactive shells we set BASH_ENV
# (e.g. podman run some_script.sh)
ENV BASH_ENV=/etc/profile.d/zzz.load_env.sh
RUN mv load_env.sh $BASH_ENV
RUN mv base.env.sh /opt/environment

WORKDIR /
RUN rm -rf /build
