# podman-hpc build -t mjkramer/2x2_sim:edepsim000 .
FROM mjkramer/2x2_sim:core000
# FROM c58defe05b10

ENV EDEPSIM=${GEN_DIR}/edep-sim/install

# This points to a MakeProject-generated library for the edep-sim output format
# See comments in 2x2_sim's run_spill_build.sh
# Also useful for 2x2_sim's admin/dump_metadata.py
ENV LIBTG4EVENT_DIR=${GEN_DIR}/libTG4Event

# FIXME: this is done in core; delete me after full rebuild
# ENV GEANT4_VERSION=10.7.4
# ENV CMAKE_PREFIX_PATH=${GEN_DIR}/geant4/install/lib64/Geant4-${GEANT4_VERSION}:$CMAKE_PREFIX_PATH

RUN mkdir -p /build
COPY edepsim.build.sh /build
RUN /build/edepsim.build.sh
