# podman-hpc build -t mjkramer/2x2_sim:edepsim007 .
FROM mjkramer/2x2_sim:core007

RUN mkdir -p /build
WORKDIR /build
COPY *.sh .

RUN cat edepsim.env.sh >> /environment

RUN ./build_edepsim.sh

WORKDIR /
RUN rm -rf /build
